Kevin_Lewis_practice-for-ch-rails-capybara-main/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "bands#index"

  resource :session, only: [:new, :create, :destroy]

  resources :users, only: [:index, :show, :new, :create] do
    get :activate, on: :collection
    post :toggle_admin, on: :member
  end

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, only: [:show, :create, :edit, :update, :destroy] do
    resources :tracks, only: [:new]
  end

  resources :tracks, only: [:show, :create, :edit, :update, :destroy]

  resources :notes, only: [:create, :destroy]
end

Kevin_Lewis_practice-for-ch-rails-capybara-main/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Music App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <div class='main-content'>
      <h1 class='main-logo'>Music App</h1>
      <% if logged_in? %>
        <nav>
          <a class='button' href="<%= bands_url %>">Take me Home</a>
          
          <div class='user-detail'>
            <p>Logged in as: <%= current_user.email %></p>
          <form action=<%= session_url %> method='post'>
            <input
              type="hidden"
              name="_method"
              value="delete">
            <input
              type="hidden"
              name="authenticity_token"
              value="<%= form_authenticity_token %>">
            <input 
              type="submit" value="Sign Out">
          </form>
          </div>
        </nav>
      <% end %>

      <% if flash[:notice] %>
        <p><%= flash[:notice] %></p>
      <% end %>

      <% if flash[:errors] %>
        <p><%= flash[:errors].join(", ") %></p>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>