Kevin_Lewis_practice-for-ch-rails-capybara-main/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "bands#index"

  resource :session, only: [:new, :create, :destroy]

  resources :users, only: [:index, :show, :new, :create] do
    get :activate, on: :collection
    post :toggle_admin, on: :member
  end

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, only: [:show, :create, :edit, :update, :destroy] do
    resources :tracks, only: [:new]
  end

  resources :tracks, only: [:show, :create, :edit, :update, :destroy]

  resources :notes, only: [:create, :destroy]
end

Kevin_Lewis_practice-for-ch-rails-capybara-main/app/models/track.rb
# == Schema Information
#
# Table name: tracks
#
#  id         :bigint           not null, primary key
#  title      :string           not null
#  album_id   :bigint           not null
#  ord        :integer          not null
#  bonus      :boolean          default(FALSE), not null
#  lyrics     :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Track < ApplicationRecord
  validates :title, :ord, presence: true
  # can't use presence validation with boolean field
  validates :bonus, inclusion: { in: [true, false] }
  validates :ord, uniqueness: { scope: :album_id }

  belongs_to :album

  has_one :band,
    through: :album,
    source: :band

  has_many :notes,
    dependent: :destroy

  after_initialize :set_defaults

  def set_defaults
    self.bonus ||= false
  end
end

Kevin_Lewis_practice-for-ch-rails-capybara-main/app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :require_admin, only: %i(new, create, edit, update, destroy)
  before_action :set_track, only: %i(show edit update destroy)

  def show
  end

  def new
    @album = Album.find(params[:album_id])
    @track = Track.new(album_id: params[:album_id])
  end

  def create
    @track = Track.new(track_params)

    if @track.save
      redirect_to track_url(@track)
    else
      @album = @track.album
      flash.now[:errors] = @track.errors.full_messages
      render :new
    end
  end

  def edit
  end

  def update
    if @track.update(track_params)
      redirect_to track_url(@track)
    else
      flash.now[:errors] = @track.errors.full_messages
      render :edit
    end
  end

  def destroy
    @track.destroy
    redirect_to album_url(@track.album_id)
  end

  private

  def set_track
    @track = Track.find(params[:id])
  end

  def track_params
    params.require(:track).permit(:album_id, :bonus, :lyrics, :title, :ord)
  end
end

Kevin_Lewis_practice-for-ch-rails-capybara-main/app/views/tracks/_form.html.erb
<% action_url = track.persisted? ? track_url(track) : tracks_url %>
<% http_method = track.persisted? ? "PATCH" : "POST" %>


<form class='form' action="<%= action_url %>" method="POST" %>
  <input type="hidden" name="_method" value="<%= http_method %>">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

<p>
  <label for='track-title'>Title</label>
  <input id='track-title' type="text" name="track[title]" value="<%= track.title %>">
</p>

<p>
<label for='track-album'>Album</label>
  <select id='track-album' name="track[album_id]">
    <% Album.all.each do |album| %>
      <option
        <%= "selected" if track.album_id == album.id %>
        value="<%= album.id %>">
        <%= album.title %>
      </option>
    <% end %>
  </select>
</p>

<p>
  <label for='track-ord'>Ord</label>
  <input id='track-ord' type="number" name="track[ord]" value="<%= track.ord %>">
</p>

<p>
  <label for="track_bonus_f">Standard</label>
  <input
    type="radio"
    name="track[bonus]"
    value="f"
    id="track_bonus_f"
    <%= "checked" if !track.bonus %>>
  <br>
  <label for="track_bonus_t">Bonus</label>
  <input
    type="radio"
    name="track[bonus]"
    value="t"
    id="track_bonus_t"
    <%= "checked" if track.bonus %>>
</p>

<p>
  <label for="track_lyrics">Lyrics</label><br>
  <textarea id="track_lyrics"
    rows="10" cols="40"
    name="track[lyrics]"><%= track.lyrics %></textarea>
</p>

  <input type="submit" value="Create Track">
</form>

Kevin_Lewis_practice-for-ch-rails-capybara-main/app/views/tracks/edit.html.erb
<h1 class='page-header'>Edit <%= @track.title %></h1>

<%= render "form", track: @track %>

Kevin_Lewis_practice-for-ch-rails-capybara-main/app/views/tracks/new.html.erb
<h1 class='page-header'>New <%= @album.title %> Track</h1>

<%= render "form", track: @track %>

Kevin_Lewis_practice-for-ch-rails-capybara-main/app/views/tracks/show.html.erb
<h1 class='page-header'><%= @track.title %></h1>

<%= ugly_lyrics(@track.lyrics) %>

<%= render "note/form", track: @track %>

<h4 class='sub-header'>Notes</h4>

<% @track.notes.each do |note| %>
  <%= render "note/note", note: note %>
<% end %>

<h4 class='sub-header'>Links</h4>
<ul class='page-links'>
  <% if current_user.admin? %>
    <li><a class='button' href="<%= edit_track_url(@track) %>">Edit Track</a></li>
    <li>
      <form action="<%= track_url(@track) %>" method="POST">
        <input type="hidden" name="_method" value="DELETE">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" >
        <input type="submit" value="Destroy Track">
      </form>
    </li>
    <li><a class='button' href="<%= users_url %>">Users</a></li>
  <% end %>
  <li><a class='button' href="<%= album_url(@track.album) %>"><%= @track.album.title %></a></li>
</ul>